// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pb/ad.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,4,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,5,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AdvertiserId  string                 `protobuf:"bytes,7,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdCampaignRequest) Reset() {
	*x = AdCampaignRequest{}
	mi := &file_pb_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdCampaignRequest) ProtoMessage() {}

func (x *AdCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdCampaignRequest.ProtoReflect.Descriptor instead.
func (*AdCampaignRequest) Descriptor() ([]byte, []int) {
	return file_pb_ad_proto_rawDescGZIP(), []int{0}
}

func (x *AdCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdCampaignRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdCampaignRequest) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *AdCampaignRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *AdCampaignRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdCampaignRequest) GetAdvertiserId() string {
	if x != nil {
		return x.AdvertiserId
	}
	return ""
}

type SyncAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAdResponse) Reset() {
	*x = SyncAdResponse{}
	mi := &file_pb_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAdResponse) ProtoMessage() {}

func (x *SyncAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAdResponse.ProtoReflect.Descriptor instead.
func (*SyncAdResponse) Descriptor() ([]byte, []int) {
	return file_pb_ad_proto_rawDescGZIP(), []int{1}
}

func (x *SyncAdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncAdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdRequest) Reset() {
	*x = DeleteAdRequest{}
	mi := &file_pb_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdRequest) ProtoMessage() {}

func (x *DeleteAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdRequest) Descriptor() ([]byte, []int) {
	return file_pb_ad_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdResponse) Reset() {
	*x = DeleteAdResponse{}
	mi := &file_pb_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdResponse) ProtoMessage() {}

func (x *DeleteAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdResponse) Descriptor() ([]byte, []int) {
	return file_pb_ad_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_ad_proto protoreflect.FileDescriptor

const file_pb_ad_proto_rawDesc = "" +
	"\n" +
	"\vpb/ad.proto\x12\x02pb\"\xd4\x01\n" +
	"\x11AdCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmedia_url\x18\x04 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"target_url\x18\x05 \x01(\tR\ttargetUrl\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\radvertiser_id\x18\a \x01(\tR\fadvertiserId\"D\n" +
	"\x0eSyncAdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\x0fDeleteAdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x10DeleteAdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2w\n" +
	"\tAdService\x123\n" +
	"\x06SyncAd\x12\x15.pb.AdCampaignRequest\x1a\x12.pb.SyncAdResponse\x125\n" +
	"\bDeleteAd\x12\x13.pb.DeleteAdRequest\x1a\x14.pb.DeleteAdResponseB\x16Z\x14social-network-go/pbb\x06proto3"

var (
	file_pb_ad_proto_rawDescOnce sync.Once
	file_pb_ad_proto_rawDescData []byte
)

func file_pb_ad_proto_rawDescGZIP() []byte {
	file_pb_ad_proto_rawDescOnce.Do(func() {
		file_pb_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_ad_proto_rawDesc), len(file_pb_ad_proto_rawDesc)))
	})
	return file_pb_ad_proto_rawDescData
}

var file_pb_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_ad_proto_goTypes = []any{
	(*AdCampaignRequest)(nil), // 0: pb.AdCampaignRequest
	(*SyncAdResponse)(nil),    // 1: pb.SyncAdResponse
	(*DeleteAdRequest)(nil),   // 2: pb.DeleteAdRequest
	(*DeleteAdResponse)(nil),  // 3: pb.DeleteAdResponse
}
var file_pb_ad_proto_depIdxs = []int32{
	0, // 0: pb.AdService.SyncAd:input_type -> pb.AdCampaignRequest
	2, // 1: pb.AdService.DeleteAd:input_type -> pb.DeleteAdRequest
	1, // 2: pb.AdService.SyncAd:output_type -> pb.SyncAdResponse
	3, // 3: pb.AdService.DeleteAd:output_type -> pb.DeleteAdResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_ad_proto_init() }
func file_pb_ad_proto_init() {
	if File_pb_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_ad_proto_rawDesc), len(file_pb_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_ad_proto_goTypes,
		DependencyIndexes: file_pb_ad_proto_depIdxs,
		MessageInfos:      file_pb_ad_proto_msgTypes,
	}.Build()
	File_pb_ad_proto = out.File
	file_pb_ad_proto_goTypes = nil
	file_pb_ad_proto_depIdxs = nil
}
